# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'Pawpulace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pawpulace

  target 'PawpulaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'RSKImageCropper'
pod 'QBImagePickerController'
